name: SportBookCompanion
options:
  bundleIdPrefix: sport.diary.companion.iosapp
  deploymentTarget:
    iOS: "16.6"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.6"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
targets:
  SportBookCompanion:
    type: application
    platform: iOS
    deploymentTarget: "16.6"
    sources:
      - path: iosApp
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: sport.diary.companion.iosapp
        PRODUCT_NAME: SportBookCompanion
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "16.6"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        DEVELOPMENT_ASSET_PATHS: '"iosApp/Preview Content"'
